---
- name: Test playbook
  hosts: localhost
  connection: local
  vars: 
    app_enviroment: "lab"
  vars_files:
    - /vagrant/secrets.yml
    - ansible/vars/main.yml
  tasks:
    - name: Visa ett meddelande
      debug:
        msg: "ansible kör från kontrollnoden!"

    - name: Visa en variavle
      debug:
        msg: "Miljö: {{ environment }}"
